import "./globals.css";

import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import localFont from "next/font/local";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { useMessages } from "next-intl";

import CookiesComponent from "@/components/shared/cookies/CookiesComponent";
import Footer from "@/components/shared/footer/Footer";
import Header from "@/components/shared/header/Header";
import OrderPopUp from "@/components/shared/pop-up/OrderPopUp";
import { routing } from "@/i18n/routing";
import { Locale } from "@/types/locale";

const gogh = localFont({
  weight: "500",
  src: "../../fonts/Gogh-ExtraBold.woff2",
  variable: "--font-gogh",
});

const manrope = Manrope({
  weight: ["400"],
  subsets: ["latin", "cyrillic"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  const messages = useMessages();

  return (
    <html lang={locale} className="scroll-smooth">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body
        className={`${gogh.variable} ${manrope.className} flex min-h-screen flex-col antialiased text-sm`}
      >
        <NextIntlClientProvider messages={messages}>
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
          <CookiesComponent />
          <OrderPopUp />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
